import { PrismaClient, Prisma } from "@prisma/client";

const prisma = new PrismaClient();

const userData: Prisma.TodosCreateInput[] = [
  {
    id: 1,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "定年後に世界一周旅行をする",
  },
  {
    id: 2,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "そのための貯金を忘れない",
  },
  {
    id: 3,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "ベトナムにもう一度行く",
  },
  {
    id: 4,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "オーロラを一度は見る",
  },
  {
    id: 5,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "貯めたマイルでビジネスクラスに乗る",
  },
  {
    id: 6,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "ギリシャの街並みを写真に収める",
  },
  {
    id: 7,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "第２の故郷(笑)であるオーストラリアに行く",
  },
  {
    id: 8,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "完成したサグラダファミリアを見に行く",
  },
  {
    id: 9,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "その道中で本場のパエリアを食べる(本当に美味いらしい)",
  },
  {
    id: 10,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "ななつ星に乗って旅行をする",
  },
  {
    id: 11,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "沖縄でダイビングをする",
  },
  {
    id: 12,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "長瀞でカヤックをする",
  },
  {
    id: 13,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "俺の運転で旅行をする",
  },
  {
    id: 14,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "冬の白川郷に泊まる",
  },
  {
    id: 15,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "４７都道府県でツーショットを撮る",
  },
  {
    id: 16,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "上色見熊野座神社神秘的な写真を撮る",
  },
  {
    id: 17,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "ミラコスタに泊まる",
  },
  {
    id: 18,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "札幌雪まつりに参加する",
  },
  {
    id: 19,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "仁淀ブルーを一緒に見に行く",
  },
  {
    id: 20,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "長崎旅行で坂の写真を２人でたくさん撮る",
  },
  {
    id: 21,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "修善寺温泉の紅葉を見に行く",
  },
  {
    id: 22,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "露天風呂付きの宿に泊まる",
  },
  {
    id: 23,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "日本列島ダーツの旅を２人でする",
  },
  {
    id: 24,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "しまなみ海道をもう一度走る",
  },
  {
    id: 25,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "屋久杉を見に行く",
  },
  {
    id: 26,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "京都桜巡りをする",
  },
  {
    id: 27,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "大阪に行ってUSJに行く",
  },
  {
    id: 28,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "リゾートに泊まって金持ちごっこをする",
  },
  {
    id: 29,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "部下の結婚式で夫婦円満の秘訣を語る",
  },
  {
    id: 30,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "ありがとうを言い合う",
  },
  {
    id: 31,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "美味しいを言い合う",
  },
  {
    id: 32,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "記念日ごとに友達にノロケ話をする",
  },
  {
    id: 33,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "スカイダイビングをする",
  },
  {
    id: 34,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "２人の似顔絵を描いてもらう",
  },
  {
    id: 35,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "宇多田ヒカルのライブを見に行く",
  },
  {
    id: 36,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "地味ハロウィンに一緒に出る",
  },
  {
    id: 37,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "今の体型を一生保つ",
  },
  {
    id: 38,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "4/25生まれを見つけたら家に招待する",
  },
  {
    id: 39,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "２人でインスタ映えする料理を作る",
  },
  {
    id: 40,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "ワカサギ釣りをする",
  },
  {
    id: 41,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "あしかがフラワーパークの大藤を見に行く",
  },
  {
    id: 42,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "アクションカメラの動画をYouTubeにあげる",
  },
  {
    id: 43,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "その再生回数が10000回を超える",
  },
  {
    id: 44,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "本で壁一面を埋める",
  },
  {
    id: 45,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "お気に入りのソファを手に入れる",
  },
  {
    id: 46,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "いい歯医者を見つける(切実)",
  },
  {
    id: 47,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "フェルメール展に行く(迅速に)",
  },
  {
    id: 48,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "本格的な占いをしてもらう",
  },
  {
    id: 49,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "浅草演芸場で落語を聞く",
  },
  {
    id: 50,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "劇団四季のミュージカルを見る",
  },
  {
    id: 51,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "藝大の文化祭に行く",
  },
  {
    id: 52,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "日記をつけ始める",
  },
  {
    id: 53,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "埼玉vs千葉の決着をつける",
  },
  {
    id: 54,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "秩父の原で蕎麦を食べる",
  },
  {
    id: 55,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "ジビエ料理を食べに行く",
  },
  {
    id: 56,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "秩父の氷柱を見に行く",
  },
  {
    id: 57,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "雲海を見に行く",
  },
  {
    id: 58,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "大相撲を見に行く",
  },
  {
    id: 59,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "御朱印集めをする",
  },
  {
    id: 60,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "獺祭を江戸切子で飲む",
  },
  {
    id: 61,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "秩父ワインをゆっくり２人で飲む",
  },
  {
    id: 62,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "これから何か共通の趣味を見つける",
  },
  {
    id: 63,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "おみくじ帖を一冊埋める",
  },
  {
    id: 64,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "東京オリンピックの何かの競技を一緒に見に行く",
  },
  {
    id: 65,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "文楽を見に行く",
  },
  {
    id: 66,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "皆野の天空のポピーを一緒に見に行く",
  },
  {
    id: 67,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "結婚10周年に氷川様に挨拶に行く",
  },
  {
    id: 68,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "豊洲市場に行って海鮮丼を食べる",
  },
  {
    id: 69,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "コスプレ写真を撮る",
  },
  {
    id: 70,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "リニューアルした鉄道博物館に行く",
  },
  {
    id: 71,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "ワセメシ有名店を制覇する",
  },
  {
    id: 72,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "ふるさと納税を楽しむ",
  },
  {
    id: 73,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "わんこそばで自分の限界に挑戦する",
  },
  {
    id: 74,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "フルマラソンを２人で走りきる",
  },
  {
    id: 75,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "ナイアガラの滝を見に行く",
  },
  {
    id: 76,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "ハンモックを部屋に入れる",
  },
  {
    id: 77,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "富士山に登る",
  },
  {
    id: 78,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "浴衣を着て花火大会に行く",
  },
  {
    id: 79,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "陶芸でお気に入り作品を見る",
  },
  {
    id: 80,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "２人でワイン作りに参加する",
  },
  {
    id: 81,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "バスケの試合を一緒に見に行く",
  },
  {
    id: 82,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "いい店を開拓してレビューを載せる",
  },
  {
    id: 83,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "「ティファニーで朝食を」を指輪をつけながら２人で見る",
  },
  {
    id: 84,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "ユーガットメールを２人で見る",
  },
  {
    id: 85,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "一軒家もしくはマンションを買って、帰りたい家にする",
  },
  {
    id: 86,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "箱根駅伝を生で見に行く",
  },
  {
    id: 87,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "お互いの親友を招待し合う",
  },
  {
    id: 88,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "お互いの両親に旅行のプレゼントをする",
  },
  {
    id: 89,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "式でお世話になった方々にお礼をする",
  },
  {
    id: 90,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "家庭菜園で育てたハーブでハーブティーをつくる",
  },
  {
    id: 91,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "地方にオーナーとして畑をもち自分の野菜が届くようにする",
  },
  {
    id: 92,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "旅行の度に写真を印刷してアルバムを作る",
  },
  {
    id: 93,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "カッコいいおじさんとおばさんになる",
  },
  {
    id: 94,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "東京タワー近くのクレッセントに行く",
  },
  {
    id: 95,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "帝国ホテルで記念日を祝う",
  },
  {
    id: 96,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "ミシュラン三ツ星の店に行く",
  },
  {
    id: 97,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "銀婚式で他人が羨むような食事をする",
  },
  {
    id: 98,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "60歳を過ぎても手を繋いで散歩をする",
  },
  {
    id: 99,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "相手よりも長生きするよう努める",
  },
  {
    id: 100,
    description: "",
    location: "",
    status: "Undone",
    todo_name: "一生、最後の最後まで幸せでいる",
  },
];

async function main() {
  console.log(`Start seeding ...`);
  for (const u of userData) {
    const todo = await prisma.todos.create({
      data: u,
    });
    console.log(`Created user with id: ${todo.id}`);
  }
  console.log(`Seeding finished.`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
